name: Render Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      deployments: write
    steps:
      - uses: JorgeLNJunior/render-deploy@v1.4.5
        with:
          service_id: ${{ secrets.FURNI_RENDER_SERVICE_ID }}
          api_key: ${{ secrets.FURNI_RENDER_API_ID }}
          clear_cache: true # Optional: Clear Render's build cache
          wait_deploy: true


