name: Render Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.FURNI_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.FURNI_RENDER_API_ID }}
          wait-for-success: true
